name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download HTML artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: website-html
          path: dist
          run_id: ${{ github.event.workflow_run.id }}

      - name: Download Functions artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: website-functions
          path: functions
          run_id: ${{ github.event.workflow_run.id }}

      - name: Download package artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: website-package
          run_id: ${{ github.event.workflow_run.id }}

      - name: Enable Corepack shims
        run: corepack enable

      - name: Install dependencies
        run: pnpm install
        
      - name: Run dev server
        run: pnpm dev
